# Generated by Django 4.1.3 on 2022-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Typ Ticketu',
                'verbose_name_plural': 'Typy Ticketów',
            },
        ),
    ]
