# Generated by Django 4.1.3 on 2022-11-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DICTIONARY", "0009_ticketsstatus_tickets_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketsstatus",
            name="status_name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
