# Generated by Django 4.1.3 on 2022-11-11 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DICTIONARY', '0010_alter_ticketsstatus_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketshistory',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_user_ticket_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
