# Generated by Django 4.1.3 on 2022-11-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DICTIONARY", "0011_ticketshistory_created_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketshistory",
            name="created_user",
        ),
        migrations.RemoveField(
            model_name="ticketshistory",
            name="ticket",
        ),
        migrations.DeleteModel(
            name="Tickets",
        ),
        migrations.DeleteModel(
            name="TicketsHistory",
        ),
    ]
