version: '3'

networks:
  itticketnet:

services:
  # mariadb:
  #   image: mariadb:latest
  #   container_name: papsi_lab_mariadb_1
  #   ports: 
  #     - "3306:3306"
  #   expose:
  #     - 3306
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=adminsql123q
  #     - MARIADB_USER=root
  #   volumes:
  #     - "./files/mysqldb:/var/lib/mysql"
  #   networks:
  #     - itticketnet
  #   healthcheck:
  #     test: "mysqladmin ping -h localhost --user=$$MARIADB_USER --password=$$MARIADB_ROOT_PASSWORD"
  #     interval: 10s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 10s

  postgres:
    image: postgres
    container_name: papsi_lab_postgres_1
    environment:
      - POSTGRES_PASSWORD=adminsql123q
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./files/postgres:/var/lib/postgresql/data
    networks:
      - itticketnet
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 2s
      timeout: 2s
      retries: 5

  pgadmin4:
    image: dpage/pgadmin4
    container_name: papsi_lab_pgadmin4_1
    environment:
      - PGADMIN_DEFAULT_EMAIL=pm@umx.pl
      - PGADMIN_DEFAULT_PASSWORD=P@ssw0rd
    ports:
      - "8080:80"
    networks:
      - itticketnet
  
  itticket:
    build: .
    #image: polipl/itticket:latest
    container_name: papsi_lab_itticket_1
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    expose:
      - 8000
      - 80
      - 443
    volumes:
      - "./ITticket/:/ITticket"
      - "./files/conf/supervisor:/etc/supervisor"
      #- "./files/conf/nginx:/etc/nginx"
    networks:
      - itticketnet
    depends_on:
      postgres:
        condition: service_healthy
    

    
