version: "3.9"

networks:
  itticketnet:

services:

  postgres:
    image: postgres
    container_name: papsi_lab_postgres_1
    environment:
      - POSTGRES_PASSWORD=adminsql123q
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./files/postgres:/var/lib/postgresql/data
    networks:
      - itticketnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  itticket:
    # build: .
    image: polipl/itticket:latest
    container_name: papsi_lab_itticket_1
    ports:
      - "8000:8000"
    environment:
      - DBNAME=itticket
      - DBUSER=itticket
      - DBPASSWORD=adminsql123q
      - DBHOST=papsi_lab_postgres_1
      - DBPORT=5432
    expose:
      - 8000
    volumes:
      - "./ITticket/:/ITticket"
    networks:
      - itticketnet
    depends_on:
      postgres:
        condition: service_healthy
    

    
