# Generated by Django 4.1.3 on 2022-11-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERVICEDESK', '0002_tickets_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
