name: IT Ticket Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build docker image
      run: docker build -t itticket .
    - 
      name: Tags
      run: docker tag itticket ${{ secrets.DOCKERHUB_USERNAME }}/itticket
    - 
      name: Push image to dockerhub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/itticket
    -
      name: Docker hub logout
      run: docker logout

