name: IT Ticket Docker Image Deploy

on:
  push:
    branches: [ "main" ]
    
    paths:
      - 'ITticket/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Take Python 3.10
      uses: actions/setup-python@v4
      with: 
        python-version: '3.10'
    - 
      name: Install requirements
      run: pip install -r requirements.txt
      working-directory: ITticket
    - 
      name: Check Lint
      run: flake8 . --ignore E501
      working-directory: ITticket


  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build docker image
      run: docker build -t itticket .
    - 
      name: Tags
      run: docker tag itticket ${{ secrets.DOCKERHUB_USERNAME }}/itticket
    - 
      name: Push image to dockerhub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/itticket
    -
      name: Docker hub logout
      run: docker logout

